on:
    repository_dispatch:
        types: [update-tokens]
        push:
            branches:
                - main
jobs:
  save_in_repo:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
        - name: Git
          run: |
              echo "${{github.event.client_payload.tokens}}" > designTokens.json
              cat designTokens.json
              git config --global user.name "github-actions[bot]"
              git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git status
              git add designTokens.json
              git commit -m "New design token"
              git push
