on:
    repository_dispatch:
        types: [update-tokens]
        push:
            branches:
                - main
env:
    payload: ${{ github.event.client_payload }}

jobs:
  save_in_repo:
    runs-on: ubuntu-latest
    steps:
      - run:
            echo "${{env.payload}}" > designTokens.json
            git add designTokens.json
            git commit -m "New design token"
            git push
